---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-opm-command-oci-ta
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: konflux
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: TODO Description
  params:
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
      type: string
#    - name: ociStorage
#      description: The OCI repository where the Trusted Artifacts are stored.
#      type: string
  results:
    - name: SOURCE_CATALOG_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with 
        the application source code with generated file-based catalog from catalog-template.yml.
  volumes:
    - name: workdir
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:635a890e9f0211b4eb5b8c811d6f06b3ed9ff7da952ebad236fbfe52ba36dbf7
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
    - name: run-opm-command
      image: quay.io/redhat-appstudio/konflux-test:v1.4.23@sha256:e451a01a24824fbac8c3a667924337f67153a5bdaa68001410183bbac37e000f
      env:
#        - name: IMAGE_URL
#          value: $(params.image-url)
#        - name: IMAGE_DIGEST
#          value: $(params.image-digest)
        - name: SOURCE_CODE_DIR
          value: /var/workdir
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        # shellcheck source=/dev/null
        . /utils.sh
        
        echo "run-opm-command - test run" >/var/workdir/source/run-opm-command-test.txt
      computeResources:
        limits:
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 2Gi
#    - name: create-trusted-artifact
#      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:edd8e3affc389320b15b9de8a5aedbf7b0463211b77c981563a2cfa20076b0c0
#      args:
#        - create
#        - --store
#        - $(params.ociStorage)
#        - $(results.SOURCE_CATALOG_ARTIFACT.path)=/var/workdir/source
#      volumeMounts:
#        - mountPath: /var/workdir
#          name: workdir
#      env:
#        - name: IMAGE_EXPIRES_AFTER
#          value: $(params.ociArtifactExpiresAfter)
#      computeResources:
#        limits:
#          memory: 3Gi
#        requests:
#          cpu: "1"
#          memory: 3Gi
